server:
  port: 8061

eureka:
  instance:
    hostname: discovery1-charles3.apps.qqd02ebq.usgovvirginia.aroapp.azure.us
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://discovery1-charles3.apps.qqd02ebq.usgovvirginia.aroapp.azure.us/eureka/
