server:
  port: 8061

eureka:
  instance:
    hostname: discovery.charles3.svc.cluster.local
  client:
    serviceUrl:
      defaultZone: https://discovery-charles3.apps.qqd02ebq.usgovvirginia.aroapp.azure.us/eureka/
