server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: https://discovery-charles3.apps.qqd02ebq.usgovvirginia.aroapp.azure.us/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: fc-sample-microservice.charles3.svc.cluster.local
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
