server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: https://discovery1-charles3.apps.qqd02ebq.usgovvirginia.aroapp.azure.us/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: sample-service
        uri: lb://sample-service
        predicates:
        - Path=/sample/**
        filters:
        - RewritePath=/sample/(?<path>.*), /$\{path}
      - id: sample-service2
        uri: lb://sample-service2
        predicates:
        - Path=/sample2/**
        filters:
        - RewritePath=/sample2/(?<path>.*), /$\{path}
