server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: https://discovery-charles3.apps.qqd02ebq.usgovvirginia.aroapp.azure.us/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: sample-service
        uri: lb://sample-service
        predicates:
        - Path=/sample/**
        filters:
        - RewritePath=/sample/(?<path>.*), /$\{path}
      - id: sample-service2
        uri: lb://sample-service2
        predicates:
        - Path=/sample2/**
        filters:
        - RewritePath=/sample2/(?<path>.*), /$\{path}
      - id: sample-service3
        uri: lb://sample-service3
        predicates:
        - Path=/sample3/**
        filters:
        - RewritePath=/sample3/(?<path>.*), /$\{path}
      - id: sample-service4
        uri: lb://sample-service4
        predicates:
        - Path=/sample4/**
        filters:
        - RewritePath=/sample4/(?<path>.*), /$\{path}
      - id: sample-service5
        uri: lb://sample-service5
        predicates:
        - Path=/sample5/**
        filters:
        - RewritePath=/sample5/(?<path>.*), /$\{path}
      - id: sample-service6
        uri: lb://sample-service6
        predicates:
        - Path=/sample6/**
        filters:
        - RewritePath=/sample6/(?<path>.*), /$\{path}
      - id: sample-service7
        uri: lb://sample-service7
        predicates:
        - Path=/sample7/**
        filters:
        - RewritePath=/sample7/(?<path>.*), /$\{path}
      - id: sample-service8
        uri: lb://sample-service8
        predicates:
        - Path=/sample8/**
        filters:
        - RewritePath=/sample8/(?<path>.*), /$\{path}
      - id: sample-service9
        uri: lb://sample-service9
        predicates:
        - Path=/sample9/**
        filters:
        - RewritePath=/sample9/(?<path>.*), /$\{path}
      - id: fc-sample-service
        uri: lb://fc-sample-service
        predicates:
        - Path=/fcSample/**
        filters:
        - RewritePath=/fcSample/(?<path>.*), /$\{path}
        
      
