server:
  port: 80

eureka:
  instance:
    hostname: sample-microservice-2v3-charles3.apps.qqd02ebq.usgovvirginia.aroapp.azure.us
  client:
    serviceUrl:
      defaultZone: discovery.charles3.svc.cluster.local
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
