server:
  port: 9001

eureka:
  instance:
    instance-id: ${spring.application.name}
    hostname: sample-microservice-3v3.charles3.svc.cluster.local
  client:
    serviceUrl:
      defaultZone: https://discovery-charles3.apps.qqd02ebq.usgovvirginia.aroapp.azure.us/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
